### ISSUE TITLE
Reward users once every 2 weeks

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/ILOCK-smartcontracts#176]
Users will get rewarded with $ILOCK once every two weeks.

**Comment by blairmunroakusa** [comment]
This is not a blockchain smartcontract feature; it must be implemented serverside (extension backend).

(Smart contracts cannot call themselves using a timer onchain...the timer and contract call must come from server.)

@DecentralizedDan @jmercouris 

Closing as 'won't do'.
