### ISSUE TITLE
Bouncer rewards server owners with $ILOCK

### ISSUE THREAD

**Issue by DecentralizedDan** [interlock-network/ILOCK-smartcontracts#180]
Server owners would get rewarded to a wallet associated with their Discord account (?)
* They get rewarded a fraction of $ILOCK per URL, up to a ceiling per two-week period (#176 )

@blairmunroakusa says this would take a couple days of work in smart contract code
* But most of the work will be in Octahedron, which will be the source of truth for who scans what and how valuable it is (per @galactic-beyond )
* Nick will pair with @jmercouris on that effort!

**Comment by blairmunroakusa** [comment]
The smart contract portion of this issue is complete. Closing ticket due to rest of work out of scope for this repo.
