### ISSUE TITLE
Create GrAE staking lifecycle diagram

### ISSUE THREAD

**Issue by blairmunroakusa** [interlock-network/ILOCK-smartcontracts#70]
Per @DecentralizedDan conversation, create diagram that depicts flow during a GrAE stake lifespan, as currently implemented in contracts.

**Comment by blairmunroakusa** [comment]
One immediate feedback tidbit on above flowchart:
...Still working on how to visualize it, but there should be something more like below...

. SS stakes against URL
. URL enters GrAE candidate stream (extension UI shows URL is NOT yet GrAE)
. BH claims staked URL as GrAE
. URL enters GrAE general stream (extension UI shows URL IS GrAE)

_where_, only BH have access to candidate stream (for claiming purposes)
_where_, both BH AND SS have access to general stream (to encourage SS to accelerate settlement process)

The simplest way I think, is to make it so that a URL is only settled if it is claimed by BH, otherwise stakes are returned after time threshold is met?

...more thoughts coming...

**Comment by DecentralizedDan** [comment]
This is a good point! We need to figure out what it takes for a URL to officially become GrAE
* This would prevent low-cost trolling
* It could be accomplished by reaching a threshold in token OR human judgment (BH)
  * I prefer a token threshold bc we can adjust the cost of making something GrAE, because we won't know at first what the right threshold is
* Then there would be a second threshold for BH judgment

So the flow:
* User stakes against a URL
  * URL goes into a stream of staked-against URLs
  * Timer starts for earning more token due to staking
* More users stake against it
  * _Do we allow users to stake "for" it yet?_
* When the URL reaches the threshold of being staked-against, it enters the GrAE stream
  * Users are encouraged to stake for and against it
* When the URL meets its next threshold -- of time or being staked on both sides, whichever comes first -- it goes to the BH jury
  * Jury makes a decision
  * Simple majority wins
  * All jurors are rewarded to avoid collaboration bn jurors??

**Comment by blairmunroakusa** [comment]
Couple response-thoughts off hand:

> More users stake against it
>     . Do we allow users to stake "for" it yet?

I say SS can only stake against, until a BH claims the URL as a GrAE. So no, I think we should NOT allow "for it" stakes at this point.

...

> All jurors are rewarded to avoid collaboration bn jurors??

Reiterating my position, I think BHs should expect two types of rewards: small-kind, for casting a jury vote, and large-kind, for claiming a GrAE and successfully settling in favor of claim.

**Comment by blairmunroakusa** [comment]
![SSCreateUser](https://user-images.githubusercontent.com/69293813/180889632-129a1c97-4d7b-4970-a4ae-d6b713832f7e.png)
![SSCreateStake](https://user-images.githubusercontent.com/69293813/180889648-395d0ea7-e56e-4c54-bf94-26488cf722e6.png)
![SSResolveStake](https://user-images.githubusercontent.com/69293813/180889680-89e2671a-8774-4493-a2ad-3309fcaaea60.png)
![SSCloseStake](https://user-images.githubusercontent.com/69293813/180889710-6db790fc-5379-4403-8825-7dd4c4119ea9.png)


```
flowchart TD

subgraph SECURITY STAKING


create(CreateUser ix) --- fill
fill(FillUser ix) --- URLbrowse(find URL browsing)
fill --- URLlist(find URL on entity list)
fill --- URLgraelist(find URL on GrAE list)
URLbrowse --- isURL1(what is URL?)
URLlist --- isURL2(what is URL?)
URLgraelist --- isURL3(what is URL?)
isURL1 --- URLsettled(settled)
isURL1 --- URLentity(entity)
isURL1 --- URLgrae(GrAE)
isURL2 --- URLentity(entity)
isURL3 --- URLgrae(GrAE)

URLentity --- isclaimed(is entity claimed?)
ishunter --- |yes|claim(ClaimEntity ix)
claim --> createstake
isclaimed --> |no|ishunter(is user bounty hunter?)


URLsettled --- createentity(CreateEntity ix)
createentity --> ishunter

URLgrae --> createstake(CreateStake ix)
isclaimed --> |yes|createstake

ishunter --> |no|createstake

end


subgraph CreateStake ix

unclaimed(unclaimed entity) --- stakeagainst(stake against)
claimed(claimed entity) --- stakeeither(stake either way)
stakeagainst --> checkguards(check guards)
stakeeither --> checkguards(check guards)

checkguards --- timemet(time threshold met?)
timemet --- |no|totalstakemet(stake threshold <br>met on both sides?)
timemet --> |yes|nostake(cannot stake)
totalstakemet --- |no|halfstakemet(stake threshold <br>met on one side?)
totalstakemet --> |yes|nostake

halfstakemet --- |no|bothsides(user can stake <br> on both sides)
halfstakemet --- |yes|onesideonly(user can stake <br>on only one side)
onesideonly --> stake(can stake)
bothsides --> stake

stake --- stakeaccount(create stake account)
nostake --- setsettling(set entity status <br>to 'settling')
setsettling --- settleentity(SettleEntity ix)
settleentity --- resolvestake(ResolveStake ix)


end


subgraph ResolveStake ix

issettled(is entity settled?) --- |no| jury

subgraph SettleEntity ix

jury(majority bounty hunter jury<br>determines entity status) --- setsettled(set entity status<br>to 'settled')

end

issettled --> |yes|stakecorrect
setsettled --> stakecorrect(was stake correct?)
stakecorrect --- |no|slash(slash stake and<br>return amount to<br>reward pool)
stakecorrect --- |yes|payreward(pay reward from <br>reward pool)
payreward --> success(increment<br>success)
success --- aboveaccuracy(user rise above <br>accuracy threshold?)
aboveaccuracy --- sethunter1(SetHunter ix<br> true)
success --- computetime


belowaccuracy --- sethunter2(SetHunter ix<br> false)
fail --- belowaccuracy(user fallbelow <br>accuracy threshold?)
fail --- computetime


slash --> fail(increment<br>fail)

computetime(compute<br>stake time) --- payyield(pay yield)
payyield --- setresolved(set stake status<br>to 'resolved')

setresolved --- closestake(CloseStake ix)

end

subgraph CloseStake ix

isresolved(is stake resolved?) --- |yes| isbh(is user<br>bounty hunter)
isresolved --- |no|waitforsettlement(wait for settlement)
isbh --> |no|closeaccount(close stake<br>account)
isbh --- |yes|isaccurate(was claim accurate?)
isaccurate --- |no|punish(punishment was <br>lost stake fromk <br>ResolveStake ix)
isaccurate ---|yes|reward(reward bounty hunter)

punish --> closeaccount
reward --> closeaccount

closeaccount --- nostakes(are there more stakes<br>associated with<br> this entity?)
nostakes --- |no|closeentity(CloseEntity ix)

end
```
